### ISSUE TITLE
Tower Range Update

### ISSUE THREAD

**Issue by rockokw** [project-brooklyn/project-brooklyn#71]
Help user visualize effective range and targetable areas of a tower by highlighting the tiles it can hit

**Comment by cb299792458** [comment]
This is coming along, but there are some complications/future issues.

- The towers won't actually be able to hit all the points within the circle, some points may be blocked by terrain (or other towers?)
- Because tiles are 1/4 as tall as they are wide, the true range would be an ellipsoid, probably doable, but might not look as nice
- Related to above, towers shoot from their tops, so this indicator will need to be offset by an uncertain amount
- Unsure if related to above two, but the ranges and radii don't seem to quite match, indicators seem bigger than expected.
![image](https://github.com/user-attachments/assets/12f01258-852c-4e2b-a4f9-20d7764aa92a)

**Comment by rockokw** [comment]
Cool, so right now you have a shell with the min and max ranges?

It might be a good time for us to think more about the towers and and targeting system. Instead of Euclidean distance, we could consider some kind of tile-based Manhattan distance instead, in such a way that reachability applies to an entire tile homogeneously. For something like that, we could highlight the relevant tiles (also considering their z-value) and won't have to worry about contorting a spherical halo.

Have you ever played Advance Wars for GBA? There was a way to see weapon range by highlighting tiles, e.g.:

![image](https://github.com/user-attachments/assets/936b9816-66f7-4a7c-9c53-78a1365ab818)

**Comment by cb299792458** [comment]
Yep, I know Advance Wars. That could make the range calculation a lot easier and improve performance, although the animations depend on the more "realistic" path, at least right now. 
In either case, I do think the range indicator should be reusable, so the player can select or mouseover an existing tower and see its range, and later its damage, cooldown, etc.
